// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWFcVoqnF-Nv9UO0hZGPRp3s66_4-Ypc',
    appId: '1:516641955922:web:2c9f5f9999e94b01b7bf8b',
    messagingSenderId: '516641955922',
    projectId: 'todo-84d57',
    authDomain: 'todo-84d57.firebaseapp.com',
    storageBucket: 'todo-84d57.firebasestorage.app',
    measurementId: 'G-MD6B4DGDG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYiux45LuPTf9XW4xndPv_oiPmnS3qpLo',
    appId: '1:516641955922:android:edf475e98dabb876b7bf8b',
    messagingSenderId: '516641955922',
    projectId: 'todo-84d57',
    storageBucket: 'todo-84d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-KAvJlyYIyLrseIdtmFqMt7OPjQiybE',
    appId: '1:516641955922:ios:ce11b5a1ab7a0020b7bf8b',
    messagingSenderId: '516641955922',
    projectId: 'todo-84d57',
    storageBucket: 'todo-84d57.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVWFcVoqnF-Nv9UO0hZGPRp3s66_4-Ypc',
    appId: '1:516641955922:web:50b61600f44bca90b7bf8b',
    messagingSenderId: '516641955922',
    projectId: 'todo-84d57',
    authDomain: 'todo-84d57.firebaseapp.com',
    storageBucket: 'todo-84d57.firebasestorage.app',
    measurementId: 'G-WKJL69MYVF',
  );
}
